require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe BirthdayCertificatesController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # BirthdayCertificate. As you add validations to BirthdayCertificate, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # BirthdayCertificatesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all birthday_certificates as @birthday_certificates" do
      birthday_certificate = BirthdayCertificate.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:birthday_certificates)).to eq([birthday_certificate])
    end
  end

  describe "GET #show" do
    it "assigns the requested birthday_certificate as @birthday_certificate" do
      birthday_certificate = BirthdayCertificate.create! valid_attributes
      get :show, {:id => birthday_certificate.to_param}, valid_session
      expect(assigns(:birthday_certificate)).to eq(birthday_certificate)
    end
  end

  describe "GET #new" do
    it "assigns a new birthday_certificate as @birthday_certificate" do
      get :new, {}, valid_session
      expect(assigns(:birthday_certificate)).to be_a_new(BirthdayCertificate)
    end
  end

  describe "GET #edit" do
    it "assigns the requested birthday_certificate as @birthday_certificate" do
      birthday_certificate = BirthdayCertificate.create! valid_attributes
      get :edit, {:id => birthday_certificate.to_param}, valid_session
      expect(assigns(:birthday_certificate)).to eq(birthday_certificate)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new BirthdayCertificate" do
        expect {
          post :create, {:birthday_certificate => valid_attributes}, valid_session
        }.to change(BirthdayCertificate, :count).by(1)
      end

      it "assigns a newly created birthday_certificate as @birthday_certificate" do
        post :create, {:birthday_certificate => valid_attributes}, valid_session
        expect(assigns(:birthday_certificate)).to be_a(BirthdayCertificate)
        expect(assigns(:birthday_certificate)).to be_persisted
      end

      it "redirects to the created birthday_certificate" do
        post :create, {:birthday_certificate => valid_attributes}, valid_session
        expect(response).to redirect_to(BirthdayCertificate.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved birthday_certificate as @birthday_certificate" do
        post :create, {:birthday_certificate => invalid_attributes}, valid_session
        expect(assigns(:birthday_certificate)).to be_a_new(BirthdayCertificate)
      end

      it "re-renders the 'new' template" do
        post :create, {:birthday_certificate => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested birthday_certificate" do
        birthday_certificate = BirthdayCertificate.create! valid_attributes
        put :update, {:id => birthday_certificate.to_param, :birthday_certificate => new_attributes}, valid_session
        birthday_certificate.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested birthday_certificate as @birthday_certificate" do
        birthday_certificate = BirthdayCertificate.create! valid_attributes
        put :update, {:id => birthday_certificate.to_param, :birthday_certificate => valid_attributes}, valid_session
        expect(assigns(:birthday_certificate)).to eq(birthday_certificate)
      end

      it "redirects to the birthday_certificate" do
        birthday_certificate = BirthdayCertificate.create! valid_attributes
        put :update, {:id => birthday_certificate.to_param, :birthday_certificate => valid_attributes}, valid_session
        expect(response).to redirect_to(birthday_certificate)
      end
    end

    context "with invalid params" do
      it "assigns the birthday_certificate as @birthday_certificate" do
        birthday_certificate = BirthdayCertificate.create! valid_attributes
        put :update, {:id => birthday_certificate.to_param, :birthday_certificate => invalid_attributes}, valid_session
        expect(assigns(:birthday_certificate)).to eq(birthday_certificate)
      end

      it "re-renders the 'edit' template" do
        birthday_certificate = BirthdayCertificate.create! valid_attributes
        put :update, {:id => birthday_certificate.to_param, :birthday_certificate => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested birthday_certificate" do
      birthday_certificate = BirthdayCertificate.create! valid_attributes
      expect {
        delete :destroy, {:id => birthday_certificate.to_param}, valid_session
      }.to change(BirthdayCertificate, :count).by(-1)
    end

    it "redirects to the birthday_certificates list" do
      birthday_certificate = BirthdayCertificate.create! valid_attributes
      delete :destroy, {:id => birthday_certificate.to_param}, valid_session
      expect(response).to redirect_to(birthday_certificates_url)
    end
  end

end
