require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe ExitPermitsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # ExitPermit. As you add validations to ExitPermit, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ExitPermitsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all exit_permits as @exit_permits" do
      exit_permit = ExitPermit.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:exit_permits)).to eq([exit_permit])
    end
  end

  describe "GET #show" do
    it "assigns the requested exit_permit as @exit_permit" do
      exit_permit = ExitPermit.create! valid_attributes
      get :show, {:id => exit_permit.to_param}, valid_session
      expect(assigns(:exit_permit)).to eq(exit_permit)
    end
  end

  describe "GET #new" do
    it "assigns a new exit_permit as @exit_permit" do
      get :new, {}, valid_session
      expect(assigns(:exit_permit)).to be_a_new(ExitPermit)
    end
  end

  describe "GET #edit" do
    it "assigns the requested exit_permit as @exit_permit" do
      exit_permit = ExitPermit.create! valid_attributes
      get :edit, {:id => exit_permit.to_param}, valid_session
      expect(assigns(:exit_permit)).to eq(exit_permit)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new ExitPermit" do
        expect {
          post :create, {:exit_permit => valid_attributes}, valid_session
        }.to change(ExitPermit, :count).by(1)
      end

      it "assigns a newly created exit_permit as @exit_permit" do
        post :create, {:exit_permit => valid_attributes}, valid_session
        expect(assigns(:exit_permit)).to be_a(ExitPermit)
        expect(assigns(:exit_permit)).to be_persisted
      end

      it "redirects to the created exit_permit" do
        post :create, {:exit_permit => valid_attributes}, valid_session
        expect(response).to redirect_to(ExitPermit.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved exit_permit as @exit_permit" do
        post :create, {:exit_permit => invalid_attributes}, valid_session
        expect(assigns(:exit_permit)).to be_a_new(ExitPermit)
      end

      it "re-renders the 'new' template" do
        post :create, {:exit_permit => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested exit_permit" do
        exit_permit = ExitPermit.create! valid_attributes
        put :update, {:id => exit_permit.to_param, :exit_permit => new_attributes}, valid_session
        exit_permit.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested exit_permit as @exit_permit" do
        exit_permit = ExitPermit.create! valid_attributes
        put :update, {:id => exit_permit.to_param, :exit_permit => valid_attributes}, valid_session
        expect(assigns(:exit_permit)).to eq(exit_permit)
      end

      it "redirects to the exit_permit" do
        exit_permit = ExitPermit.create! valid_attributes
        put :update, {:id => exit_permit.to_param, :exit_permit => valid_attributes}, valid_session
        expect(response).to redirect_to(exit_permit)
      end
    end

    context "with invalid params" do
      it "assigns the exit_permit as @exit_permit" do
        exit_permit = ExitPermit.create! valid_attributes
        put :update, {:id => exit_permit.to_param, :exit_permit => invalid_attributes}, valid_session
        expect(assigns(:exit_permit)).to eq(exit_permit)
      end

      it "re-renders the 'edit' template" do
        exit_permit = ExitPermit.create! valid_attributes
        put :update, {:id => exit_permit.to_param, :exit_permit => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested exit_permit" do
      exit_permit = ExitPermit.create! valid_attributes
      expect {
        delete :destroy, {:id => exit_permit.to_param}, valid_session
      }.to change(ExitPermit, :count).by(-1)
    end

    it "redirects to the exit_permits list" do
      exit_permit = ExitPermit.create! valid_attributes
      delete :destroy, {:id => exit_permit.to_param}, valid_session
      expect(response).to redirect_to(exit_permits_url)
    end
  end

end
